---
deployment:
  tasks:
    - export DEPLOYPATH=/home/everllub/public_html/
    - /bin/cp -R 404.html $DEPLOYPATH
    - /bin/cp -R about $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R bankruptcy-seo $DEPLOYPATH
    - /bin/cp -R blog $DEPLOYPATH
    - /bin/cp -R business-law-seo $DEPLOYPATH
    - /bin/cp -R case-studies $DEPLOYPATH
    - /bin/cp -R components $DEPLOYPATH
    - /bin/cp -R contact-handler.php $DEPLOYPATH
    - /bin/cp -R contact-us $DEPLOYPATH
    - /bin/cp -R criminal-defense-seo $DEPLOYPATH
    - /bin/cp -R delaware-seo $DEPLOYPATH
    - /bin/cp -R dubai-seo $DEPLOYPATH
    - /bin/cp -R employment-law-seo $DEPLOYPATH
    - /bin/cp -R estate-probate-seo $DEPLOYPATH
    - /bin/cp -R family-law-seo $DEPLOYPATH
    - /bin/cp -R faq $DEPLOYPATH
    - /bin/cp -R immigration-seo $DEPLOYPATH
    - /bin/cp -R index.html $DEPLOYPATH
    - /bin/cp -R locations $DEPLOYPATH
    - /bin/cp -R london-seo $DEPLOYPATH
    - /bin/cp -R melbourne-seo $DEPLOYPATH
    - /bin/cp -R personal-injury-seo $DEPLOYPATH
    - /bin/cp -R pricing $DEPLOYPATH
    - /bin/cp -R robots.txt $DEPLOYPATH
    - /bin/cp -R seo-agency-for-law-firm-lagos $DEPLOYPATH
    - /bin/cp -R services $DEPLOYPATH
    - /bin/cp -R sitemap.xml $DEPLOYPATH
    - /bin/cp -R .htaccess $DEPLOYPATH
